### ISSUE TITLE
Update 577 Floater

### ISSUE THREAD

**Issue by amarjandu** [ucsc-cgp/team-redwood#15]
- [x] Create Group Email account team-redwood@ucsc.edu https://its.ucsc.edu/google/groups.html
- [x] Connect group email with GitHub / ZenHub / Graphana PROD metric
- [x] Shortcut these on 577 Floater
- [ ] Create Process kill for ZOOM on 577 at 12:15pm (in-case standup runs long)

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/RWD-16)
┆Project Name: Team Redwood
┆Issue Number: RWD-16

**Comment by amarjandu** [comment]
created github account https://github.com/team-redwood
created gmail account: `team-redwood-group@ucsc.edu`

received account from mattW for Graphana, awaiting email from github support.

**Comment by amarjandu** [comment]
## Notes 4/3/19 : 9:32 AM

### Complete
created team.redwood.ucsc@gmail.com email for github usage.
added 2step to github team-redwood-group@ucsc.edu
stored recovery passwords within 1password manager
added graphana dashboards (prod/dev) to 577 floater.
added zenhub dashboards ( burndown + velocity)
added firefox tab cycler to shift through dashboards

### In Progress
NA
### TODO
NA
### Awaiting 
NA
